/* Персонажи The Mandela Catalogue — досье для трибьют-архива.
   Краткий пересказ ролей по публичному сюжету сериала. */
const CHARACTERS = {
  mark: {
    id: "mark",
    name: "Mark Heathcliff",
    nameRu: "Марк Хитклифф",
    role: "Жертва Vol.1",
    status: "МЁРТВ / ДЕЛО-ОБРАЗЕЦ",
    danger: 4,
    seed: 1101,
    photo: "assets/portraits/mark_photo.jpg",
    photoAlt: "assets/portraits/mark_alt.jpg",
    alternate: false,
    quote: "Я хочу проснуться.",
    dossier:
      "Центральная жертва Vol.1. Ночью получает звонок от «Сезара Торреса», записывает происходящее дома и сталкивается с Альтернатом. Его кассеты изымает MCPD. Становится одним из первых полных доказательств, что угроза — не легенда.",
    tags: ["Vol.1", "жертва", "камера"],
  },
  cesar: {
    id: "cesar",
    name: "Cesar Torres",
    nameRu: "Сезар Торрес",
    role: "Друг Марка / Type Two",
    status: "ИДЕНТИЧНОСТЬ УНИЧТОЖЕНА",
    danger: 5,
    seed: 2202,
    photo: "assets/portraits/cesar_photo.jpg",
    photoAlt: "assets/portraits/cesar_alt.jpg",
    alternate: true,
    quote: "Марк… мне нужна помощь. Открой дверь.",
    dossier:
      "Лучший друг Марка. В Vol.1 его голос и облик использует Альтернат, чтобы добиться проникновения. В каталоге имя Сезара навсегда связано с подменой: две карточки, одна ложь.",
    tags: ["Vol.1", "Alternate", "голос"],
  },
  thatcher: {
    id: "thatcher",
    name: "Thatcher Davis",
    nameRu: "Тэтчер Дэвис",
    role: "Лейтенант MCPD",
    status: "ВЕДЁТ ВОЙНУ В ОДИНОЧКУ",
    danger: 2,
    seed: 3303,
    photo: "assets/portraits/thatcher_photo.jpg",
    photoAlt: "assets/portraits/thatcher_alt.jpg",
    alternate: false,
    quote: "Это уже не «религиозная истерия».",
    dossier:
      "Полицейский округа Мандела. Расследует дом Хитклиффа, работает с кассетами и последующими волнами исчезновений. Один из немногих, кто пытается вести учёт, пока округ осыпается.",
    tags: ["MCPD", "Vol.1+", "расследование"],
  },
  adam: {
    id: "adam",
    name: "Adam Murray",
    nameRu: "Адам Мюррей",
    role: "Bythorne / оператор",
    status: "СКОМПРОМЕТИРОВАН?",
    danger: 4,
    seed: 4404,
    photo: "assets/portraits/adam_photo.jpg",
    photoAlt: "assets/portraits/adam_alt.jpg",
    alternate: false,
    quote: "Ты его видишь?",
    dossier:
      "Ключевая фигура Vol.2 и поздних томов. Вместе с Джоной Маршаллом снимает аномалии. Слишком часто смотрит в объектив. В архиве его статус двоится: охотник за правдой или тот, кого правда уже переписала.",
    tags: ["Vol.2", "камера", "Bythorne"],
  },
  jonah: {
    id: "jonah",
    name: "Jonah Marshall",
    nameRu: "Джона Маршалл",
    role: "Напарник Адама",
    status: "ХОТЕЛ УЙТИ РАНЬШЕ",
    danger: 3,
    seed: 5505,
    photo: "assets/portraits/jonah_photo.jpg",
    photoAlt: "assets/portraits/jonah_alt.jpg",
    alternate: false,
    quote: "Нам надо уходить.",
    dossier:
      "Партнёр Адама в Bythorne Paranormal Society. На записи Vol.2 — голос осторожности. Разделение, рации и чужие голоса делают его одной из самых уязвимых точек экспедиции.",
    tags: ["Vol.2", "рация", "Bythorne"],
  },
  sarah: {
    id: "sarah",
    name: "Sarah Heathcliff",
    nameRu: "Сара Хитклифф",
    role: "Сестра Марка",
    status: "СОПРОТИВЛЯЕТСЯ ГОЛОСАМ",
    danger: 2,
    seed: 6606,
    photo: "assets/portraits/sarah_photo.jpg",
    photoAlt: "assets/portraits/sarah_alt.jpg",
    alternate: false,
    quote: "Брат не стал бы так улыбаться.",
    dossier:
      "Сестра Марка Хитклиффа. После Vol.1 живёт внутри последствий: звонки «брата», сверка лиц, невозможность доверять знакомым голосам. В поздних материалах — пример того, как выживают те, кто не открывает.",
    tags: ["семья", "Vol.1+", "сверка"],
  },
  dave: {
    id: "dave",
    name: "Dave Lee",
    nameRu: "Дейв Ли",
    role: "Медиа / распространение лент",
    status: "АРХИВ ВНЕ АРХИВА",
    danger: 2,
    seed: 7707,
    photo: "assets/portraits/dave_photo.jpg",
    photoAlt: "assets/portraits/dave_alt.jpg",
    alternate: false,
    quote: "Если ролик просили не смотреть — его уже кто-то посмотрел.",
    dossier:
      "Связан с разбором и оборотом аномальных записей. Через таких людей плёнки Vol.2 уходят дальше официальных полок MCPD — в сеть, в чужие ночи, в новые копии страха.",
    tags: ["медиа", "плёнка", "Vol.2"],
  },
  ruth: {
    id: "ruth",
    name: "Ruth Weaver",
    nameRu: "Рут Уивер",
    role: "Сотрудник MCPD",
    status: "ФИКСИРУЕТ ЛИНИЮ 911",
    danger: 2,
    seed: 8808,
    photo: "assets/portraits/ruth_photo.jpg",
    photoAlt: "assets/portraits/ruth_alt.jpg",
    alternate: false,
    quote: "Лейтенант, это снова тот же голос.",
    dossier:
      "Работает с Тэтчером Дэвисом. Помогает вести звонки, совпадения и бумажный след катастрофы, пока округ ещё делает вид, что у катастрофы есть канцелярия.",
    tags: ["MCPD", "линия", "Vol.1+"],
  },
  gabriel: {
    id: "gabriel",
    name: "\"Gabriel\" / The Intruder",
    nameRu: "«Гавриил» / Вторженец",
    role: "Ложный архангел",
    status: "ИСТОЧНИК ПЕРВОЙ ЛЖИ",
    danger: 5,
    seed: 9999,
    photo: "assets/portraits/gabriel_photo.jpg",
    photoAlt: "assets/portraits/gabriel_alt.jpg",
    alternate: true,
    quote: "Think of someone you love…",
    dossier:
      "Сущность из пролога (Overcast) и сквозной мифологии сериала. Выдаёт себя за божественного вестника, использует любовь и веру как инструмент копирования. Не «просто демон» — архитектор доверия, из которого вырастают Альтернаты.",
    tags: ["Overcast", "Intruder", "запрещено"],
  },
  alternate: {
    id: "alternate",
    name: "Alternate (Type Two)",
    nameRu: "Альтернат (тип II)",
    role: "Имитатор человека",
    status: "АКТИВНАЯ УГРОЗА",
    danger: 5,
    seed: 6666,
    photo: "assets/portraits/alternate_photo.jpg",
    photoAlt: "assets/portraits/alternate_alt.jpg",
    alternate: true,
    quote: "Мы можем быть тем, кого ты любишь.",
    dossier:
      "Классификация APS: копирует голос раньше лица; тело «чуть мимо»; цель — замещение. Vol.1 показывает дверь. Vol.2 — камеру. Поздние тома — целый округ, где подмена становится нормой.",
    tags: ["APS", "Type 2", "имитация"],
  },
};

const CHARACTER_ORDER = [
  "gabriel",
  "mark",
  "cesar",
  "thatcher",
  "ruth",
  "sarah",
  "adam",
  "jonah",
  "dave",
  "alternate",
];
