/* Mandela Catalogue character dossiers — fan tribute / archive UI.
   Descriptions summarize publicly known story roles; no copyrighted assets. */
const CHARACTERS = {
  mark: {
    id: "mark",
    name: "Mark Heathcliff",
    nameRu: "Марк Хитклифф",
    role: "Житель округа / свидетель",
    status: "ПРОПАЛ / ДЕЛО ЗАКРЫТО",
    danger: 4,
    seed: 1101,
    alternate: false,
    quote: "Он стоит у двери. Он говорит голосом Сезара.",
    dossier:
      "Друг Сезара Торреса. Получил ночной звонок и столкнулся с Альтернатом у собственного дома. В архиве APS его записи помечены как «критический инцидент проникновения».",
    tags: ["Vol.1", "телефон", "дверь"],
  },
  cesar: {
    id: "cesar",
    name: "Cesar Torres",
    nameRu: "Сезар Торрес",
    role: "Друг Марка / подмена?",
    status: "ИДЕНТИЧНОСТЬ СПОРНА",
    danger: 5,
    seed: 2202,
    alternate: true,
    quote: "Открой дверь, Марк. Мне нужна помощь.",
    dossier:
      "Голос Сезара стал одним из первых подтверждённых случаев голосовой имитации. В каталоге две карточки с одним именем — и только одна должна существовать.",
    tags: ["Vol.1", "Alternate", "голос"],
  },
  thatcher: {
    id: "thatcher",
    name: "Thatcher Davis",
    nameRu: "Тэтчер Дэвис",
    role: "Лейтенант полиции округа Мандела",
    status: "АКТИВЕН / ВЫГОРЕВШИЙ",
    danger: 2,
    seed: 3303,
    alternate: false,
    quote: "Мы больше не называем их «демонами» в отчётах.",
    dossier:
      "Ведёт дела по Альтернатам, когда официальная линия ещё притворяется, что это «религиозная истерия». Ночные смены, кассеты, пустые дома.",
    tags: ["MCPD", "расследование"],
  },
  adam: {
    id: "adam",
    name: "Adam Murray",
    nameRu: "Адам Мюррей",
    role: "Охотник за аномалиями / Bythorne",
    status: "НЕСТАБИЛЕН",
    danger: 3,
    seed: 4404,
    alternate: false,
    quote: "Если камера видит его — значит, он уже близко.",
    dossier:
      "Работает с доказательствами на плёнке. Слишком часто смотрит туда, куда APS просит не смотреть. Связан с расследованиями после первых волн.",
    tags: ["Vol.2+", "камера"],
  },
  jonah: {
    id: "jonah",
    name: "Jonah Marshall",
    nameRu: "Джона Маршалл",
    role: "Партнёр Адама",
    status: "ПОД УГРОЗОЙ",
    danger: 3,
    seed: 5505,
    alternate: false,
    quote: "Не оставляй меня одного с этим каналом.",
    dossier:
      "Напарник в полевых выходах. В архивных пометках — частые упоминания паники, раций и просьб не разделяться.",
    tags: ["Vol.2+", "рация"],
  },
  sarah: {
    id: "sarah",
    name: "Sarah Heathcliff",
    nameRu: "Сара Хитклифф",
    role: "Сестра Марка",
    status: "СВЯЗАНА С ДЕЛОМ",
    danger: 2,
    seed: 6606,
    alternate: false,
    quote: "Брат не стал бы так улыбаться.",
    dossier:
      "Фигурирует в семейных записях Хитклиффов. Архив рекомендует сверку портретов родственников при любом «возвращении» пропавших.",
    tags: ["семья", "сверка"],
  },
  dave: {
    id: "dave",
    name: "Dave Lee",
    nameRu: "Дейв Ли",
    role: "Оператор / медиа-архив",
    status: "АРХИВНОЕ ЛИЦО",
    danger: 2,
    seed: 7707,
    alternate: false,
    quote: "Если ролик просили не смотреть — его уже кто-то посмотрел.",
    dossier:
      "Связан с распространением и разбором аномальных записей. В локальном архиве — куратор «неофициальных» плёнок.",
    tags: ["медиа", "плёнка"],
  },
  ruth: {
    id: "ruth",
    name: "Ruth Weaver",
    nameRu: "Рут Уивер",
    role: "Сотрудник MCPD",
    status: "В ДОСЬЕ",
    danger: 2,
    seed: 8808,
    alternate: false,
    quote: "Лейтенант, это снова тот же голос на линии.",
    dossier:
      "Упоминается в полицейских материалах округа. Помогает фиксировать звонки и совпадения лиц.",
    tags: ["MCPD", "линия"],
  },
  gabriel: {
    id: "gabriel",
    name: "\"Gabriel\"",
    nameRu: "«Гавриил»",
    role: "Ложный архангел / манипулятор",
    status: "НЕ КЛАССИФИЦИРОВАН КАК ЧЕЛОВЕК",
    danger: 5,
    seed: 9999,
    alternate: true,
    quote: "Think of someone you love…",
    dossier:
      "Сущность, выдающая себя за божественного вестника. В образовательных плёнках APS — источник «библейских» подмен и первой волны страха. Не смотрите. Не слушайте до конца.",
    tags: ["Intruder", "Vol.1", "запрещено"],
  },
  alternate: {
    id: "alternate",
    name: "Type Two Alternate",
    nameRu: "Альтернат (тип II)",
    role: "Имитатор",
    status: "АКТИВНАЯ УГРОЗА",
    danger: 5,
    seed: 6666,
    alternate: true,
    quote: "Мы можем быть тем, кого ты любишь.",
    dossier:
      "Копирует голос раньше лица. Лицо всегда чуть мимо: глаза, улыбка, задержка в отражении. Правило APS: не открывать, не отвечать, не смотреть в глаза.",
    tags: ["APS", "имитация"],
  },
};

const CHARACTER_ORDER = [
  "mark",
  "cesar",
  "thatcher",
  "sarah",
  "adam",
  "jonah",
  "dave",
  "ruth",
  "gabriel",
  "alternate",
];
